input_data_path: "data/raw/heart.csv"
output_model_path: "saved_models/LogReg_classifier.pkl"
metric_path: "saved_models/lr_metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 17
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "thal"
    - "slope"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "ca"
  features_to_drop:
    - "ca"
  target_col: "target"

