apiVersion: v1
kind: ReplicaSet
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
replicas: 3
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      name: fastapi-ml
      labels:
        app: fastapi-ml
    spec:
      containers:
        - image: shokhan/made_ml_prod_hw2_online_inference:v1
          name: fastapi-ml
          ports:
            - containerPort: 8000

