apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: shokhan/made_ml_prod_hw2_online_inference:latest
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "10Gi"
          cpu: "500m"
